services:
  dev-database:
    extends:
      file: compose.dev.yaml
      service: dev
    secrets:
      - db_password
    environment:
      TZ: "Asia/Tokyo"

secrets:
   db_password:
     file: ./.db_password
