using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Examples.CodeGenerator.Roslyn.Recipes;

[Generator]
public class EnumDescriptionGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Automatically generated marker attribute code
    /// </summary>
    private const string AttributeSource = """
        // <auto-generated/>
        namespace Examples.CodeGenerator.Generated
        {
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Enum, Inherited = false, AllowMultiple = false)]
            internal sealed class GenerateDescriptionAttribute : global::System.Attribute
            {
                public GenerateDescriptionAttribute() { }
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. First, add the marker attribute source code itself to the project.
        context.RegisterPostInitializationOutput(postInitializationContext =>
        {
            postInitializationContext.AddEmbeddedAttributeDefinition();
            postInitializationContext.AddSource("GenerateDescriptionAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8));
        });

        // 2. Efficiently extract INamedTypeSymbol with attributes
        IncrementalValuesProvider<INamedTypeSymbol> enumDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: "Examples.CodeGenerator.Generated.GenerateDescriptionAttribute",
                predicate: static (node, _) => true,
                transform: static (context, _) => (INamedTypeSymbol)context.TargetSymbol);

        IncrementalValueProvider<(Compilation Left, ImmutableArray<INamedTypeSymbol> Right)> compilationAndEnums =
            context.CompilationProvider.Combine(enumDeclarations.Collect());

        // 3. Source code generation process
        context.RegisterSourceOutput(compilationAndEnums,
            static (ctx, source) => Execute(source.Left, source.Right, ctx));
    }

    private static readonly Regex SummaryRegex = new Regex(
         @"<summary>(.*?)</summary>",
         RegexOptions.Singleline | RegexOptions.Compiled);

    private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol> enums, SourceProductionContext context)
    {
        if (enums.IsEmpty) return;

        // Get marker attribute type symbol
        INamedTypeSymbol? attributeSymbol = compilation.GetTypeByMetadataName(
                "Examples.CodeGenerator.Generated.GenerateDescriptionAttribute");
        if (attributeSymbol is null) { return; }

        foreach (var enumSymbol in enums)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            // Strictly check whether the target marker attribute is really assigned
            bool hasAttribute = enumSymbol.GetAttributes()
                .Any(ad => SymbolEqualityComparer.Default.Equals(ad.AttributeClass, attributeSymbol));

            if (!hasAttribute)
            {
                continue;
            }

            var namespaceName = enumSymbol.ContainingNamespace.ToDisplayString();
            var fullEnumName = enumSymbol.ToDisplayString();
            var extensionClassName = ToClassName(namespaceName, fullEnumName);

            List<string> caseStatements = [];

            // Output each member of Enum as a case of switch expression
            foreach (var member in enumSymbol.GetMembers().OfType<IFieldSymbol>())
            {
                var summary = member.GetDocumentationCommentXml();
                var description = member.Name;

                if (!string.IsNullOrEmpty(summary))
                {
                    var match = SummaryRegex.Match(summary);
                    if (match.Success)
                    {
                        var rawText = match.Groups[1].Value.Trim();

                        description = Escape(rawText);
                    }
                }

                caseStatements.Add($@"           {fullEnumName}.{member.Name} => ""{description}"",");
            }

            var source = $$"""
                // <auto-generated/>
                namespace {{namespaceName}}
                {
                    public static class {{extensionClassName}}GeneratedExtensions
                    {
                        public static string GetDescription(this {{fullEnumName}} value) => value switch
                        {
                {{string.Join("\n", caseStatements)}}
                            _ => value.ToString()
                        };
                    }
                }
                """;

            context.AddSource($"{extensionClassName}GeneratedExtensions.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }

        static string ToClassName(string namespaceName, string fullEnumName)
        {
            var withoutNamespace = fullEnumName.StartsWith(namespaceName + ".")
                ? fullEnumName.Substring(namespaceName.Length + 1)
                : fullEnumName;

            return withoutNamespace.Replace(".", "_"); ;
        }

        static string Escape(string rawText)
        {
            var lines = rawText.Split(["\r\n", "\r", "\n"], StringSplitOptions.None)
                .Select(line => line.Replace("\"", "\\\"").Trim());
            return string.Join("\\n ", lines);
        }
    }
}
